### ISSUE TITLE
`open_http': 404 Not Found (OpenURI::HTTPError)

### ISSUE THREAD

**Issue by nhjiejan** [inspec/inspec-azure#184] opened 2019-07-09 15:34 UTC
# Describe the problem
Issue when attemping to run ```inspec exec my-profile -t azure://```

get the following error:
```
Traceback (most recent call last):
        35: from /usr/local/bundle/bin/inspec:23:in `<main>'
        34: from /usr/local/bundle/bin/inspec:23:in `load'
        33: from /usr/local/bundle/gems/inspec-3.9.3/bin/inspec:12:in `<top (required)>'
        32: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        31: from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        30: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        29: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        28: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/cli.rb:265:in `exec'
        27: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/runner.rb:116:in `run'
        26: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/runner.rb:87:in `load'
        25: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/runner.rb:87:in `each'
        24: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/runner.rb:91:in `block in load'
        23: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/runner.rb:140:in `write_lockfile'
        22: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/profile.rb:522:in `generate_lockfile'
        21: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/dependencies/dependency_set.rb:89:in `vendor'
        20: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/dependencies/resolver.rb:31:in `resolve'
        19: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/dependencies/resolver.rb:59:in `resolve'
        18: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/dependencies/resolver.rb:59:in `each'
        17: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/dependencies/resolver.rb:67:in `block in resolve'
        16: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/dependencies/requirement.rb:80:in `resolved_source'
        15: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/cached_fetcher.rb:22:in `resolved_source'
        14: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/cached_fetcher.rb:39:in `fetch'
        13: from /usr/local/bundle/gems/inspec-3.9.3/lib/inspec/cached_fetcher.rb:32:in `cache_key'
        12: from /usr/local/bundle/gems/inspec-3.9.3/lib/fetchers/url.rb:117:in `cache_key'
        11: from /usr/local/bundle/gems/inspec-3.9.3/lib/fetchers/url.rb:132:in `sha256'
        10: from /usr/local/bundle/gems/inspec-3.9.3/lib/fetchers/url.rb:152:in `temp_archive_path'
         9: from /usr/local/bundle/gems/inspec-3.9.3/lib/fetchers/url.rb:198:in `download_archive_to_temp'
         8: from /usr/local/bundle/gems/inspec-3.9.3/lib/fetchers/url.rb:216:in `open_via_uri'
         7: from /usr/local/lib/ruby/2.6.0/open-uri.rb:35:in `open'
         6: from /usr/local/lib/ruby/2.6.0/open-uri.rb:736:in `open'
         5: from /usr/local/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
         4: from /usr/local/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
         3: from /usr/local/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
         2: from /usr/local/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
         1: from /usr/local/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
/usr/local/lib/ruby/2.6.0/open-uri.rb:378:in `open_http': 404 Not Found (OpenURI::HTTPError)
```

**Comment by riponbanik** [comment] 2019-09-17 04:38
I am having same issue, could it be due to enterprise proxy?

**Comment by r-fennell** [comment] 2019-11-27 16:45
Hi @nhjiejan - can you confirm if this is still an issue with the latest version of inspec & inspec-azure? There isn't enough information in this report to either reproduce or investigate this issue.

**Comment by liliazk** [comment] 2019-12-16 11:55
Hi,
I have the same error when I execute: 
inspec exec /home/sysadmin/my-azureTests/inspec.yml -t azure://

Traceback (most recent call last):
	38: from /usr/bin/inspec:185:in `<main>'
	37: from /usr/bin/inspec:185:in `load'
	36: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.18.39/bin/inspec:11:in `<top (required)>'
	35: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/base_cli.rb:33:in `start'
	34: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	33: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	32: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	31: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	30: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/cli.rb:287:in `exec'
	29: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/runner.rb:129:in `run'
	28: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/runner.rb:101:in `load'
	27: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/runner.rb:101:in `each'
	26: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/runner.rb:106:in `block in load'
	25: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/profile.rb:493:in `locked_dependencies'
	24: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/profile.rb:549:in `load_dependencies'
	23: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/profile.rb:525:in `lockfile'
	22: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/profile.rb:538:in `generate_lockfile'
	21: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/dependencies/dependency_set.rb:90:in `vendor'
	20: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/dependencies/resolver.rb:30:in `resolve'
	19: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/dependencies/resolver.rb:59:in `resolve'
	18: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/dependencies/resolver.rb:59:in `each'
	17: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/dependencies/resolver.rb:67:in `block in resolve'
	16: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/dependencies/requirement.rb:83:in `resolved_source'
	15: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/cached_fetcher.rb:21:in `resolved_source'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/cached_fetcher.rb:38:in `fetch'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/inspec/cached_fetcher.rb:31:in `cache_key'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/fetchers/url.rb:114:in `cache_key'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/fetchers/url.rb:130:in `sha256'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/fetchers/url.rb:150:in `temp_archive_path'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/fetchers/url.rb:197:in `download_archive_to_temp'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.39/lib/fetchers/url.rb:215:in `open_via_uri'
	 7: from /opt/inspec/embedded/lib/ruby/2.6.0/open-uri.rb:35:in `open'
	 6: from /opt/inspec/embedded/lib/ruby/2.6.0/open-uri.rb:736:in `open'
	 5: from /opt/inspec/embedded/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
	 4: from /opt/inspec/embedded/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
	 3: from /opt/inspec/embedded/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
	 2: from /opt/inspec/embedded/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
	 1: from /opt/inspec/embedded/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
/opt/inspec/embedded/lib/ruby/2.6.0/open-uri.rb:378:in `open_http': 404 Not Found (OpenURI::HTTPError)

I use :
* ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
* inspec 4.18.39

**Comment by rmoles** [comment] 2020-01-28 16:36
Hi @nhjiejan would you be able to confirm whether you are still experiencing this issue?

**Comment by rmoles** [comment] 2020-01-28 16:40
@liliazk, it looks as though there may be an error in the command that you are running. Instead of passing in the path to the inspec.yml it should be the path to where the Inspec profile lives eg. `inspec exec /home/sysadmin/my-azureTests -t azure://`
Also, be sure to check that you have the inspec-azure resource pack dependency listed in the inspec.yml.
I would suggest taking a look at the README here: https://github.com/inspec/inspec-azure/blob/master/README.md#create-a-new-profile

**Comment by rmoles** [comment] 2020-09-24 13:23
Hi, @nhjiejan, @riponbanik, @liliazk. Since we are unable to reproduce this issue with the information supplied and there hasn't been any response on this I am going to close this issue.
Feel free to re-open if this is still an issue. Thanks!

**Closed by rmoles** 2020-09-24 13:23 UTC
