### ISSUE TITLE
Executing kitchen - cannot load such file -- active_support/core_ext/hash

### ISSUE THREAD

**Issue by nukdcbear** [inspec/inspec-azure#216] opened 2019-10-31 19:13 UTC
Running kitchen on terraform code via kitchen-terraform v4.9 when execute bundle exec kitchen verify get:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [cannot load such file -- active_support/core_ext/hash] on default-terraform
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Kitchen should execute inspec-azure to verify the Azure resources created via Terraform. 

Using Terraform 0.12.10

Gemfile:
```
# ruby '2.5.3'

source "https://rubygems.org/" do
  gem 'kitchen-terraform', '4.9.0'
  gem "inspec", "~> 3.4.1"
end
```

kitchen.yml:

```
driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform

platforms:
  - name: terraform

suites:
  - name: default
    driver:
      root_module_directory: test/fixtures
    verifier:
      systems:
        - name: default
          backend: azure
          path: test/integration/default
```

inspec.yml:
```
---
name: default
depends:
  - inspec-azure:
    git: https://github.com/inspec/inspec-azure.git
```

Debug output:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [cannot load such file -- active_support/core_ext/hash] on default-terraform
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [cannot load such file -- active_support/core_ext/hash] on default-terraform
D      ----------------------
D      ------Backtrace-------
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:184:in `report_errors'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:175:in `run_action'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command/action.rb:36:in `block in call'
D      D:/Ruby25-x64/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command/action.rb:34:in `call'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/cli.rb:52:in `perform'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/bin/kitchen:13:in `block in <top (required)>'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/bin/kitchen:13:in `<top (required)>'
D      D:/Ruby25-x64/bin/kitchen:23:in `load'
D      D:/Ruby25-x64/bin/kitchen:23:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #verify action: [cannot load such file -- active_support/core_ext/hash] on default-terraform
D      ----------------------
D      ------Backtrace-------
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:14:in `require'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:14:in `require'
D      libraries/support/azure/queue.rb:5:in `create'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:27:in `eval'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:27:in `require'
D      libraries/support/azure.rb:9:in `create'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:27:in `eval'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:27:in `require'
D      libraries/azurerm_resource.rb:3:in `create'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:27:in `eval'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:27:in `require'
D      libraries/azurerm_ad_user.rb:3:in `load_with_context'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile_context.rb:160:in `instance_eval'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile_context.rb:160:in `load_with_context'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile_context.rb:149:in `load_library_file'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile_context.rb:136:in `block in load_libraries'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile_context.rb:134:in `each'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile_context.rb:134:in `load_libraries'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile.rb:256:in `load_libraries'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile.rb:248:in `block in load_libraries'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile.rb:233:in `each'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile.rb:233:in `each_with_index'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile.rb:233:in `load_libraries'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/runner.rb:87:in `block in load'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/runner.rb:81:in `each'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/runner.rb:81:in `load'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/runner.rb:110:in `run'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/terraform/inspec.rb:46:in `exec'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/terraform/inspec_without_hosts.rb:29:in `exec'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/terraform/system.rb:87:in `execute_inspec'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/terraform/system.rb:74:in `verify'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/verifier/terraform.rb:155:in `verify'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/verifier/terraform.rb:162:in `block in verify_systems'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/verifier/terraform.rb:161:in `each'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/verifier/terraform.rb:161:in `verify_systems'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/verifier/terraform.rb:91:in `call'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:459:in `block in verify_action'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:552:in `synchronize_or_call'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:514:in `block in action'
D      D:/Ruby25-x64/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:513:in `action'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:451:in `verify_action'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:381:in `block in transition_to'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:380:in `each'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:380:in `transition_to'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:162:in `verify'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:198:in `public_send'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:198:in `run_action_in_thread'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #verify action: [cannot load such file -- active_support/core_ext/hash]
D      ----------------------
D      ------Backtrace-------
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:14:in `require'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:14:in `require'
D      libraries/support/azure/queue.rb:5:in `create'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:27:in `eval'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:27:in `require'
D      libraries/support/azure.rb:9:in `create'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:27:in `eval'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:27:in `require'
D      libraries/azurerm_resource.rb:3:in `create'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:27:in `eval'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/dsl_shared.rb:27:in `require'
D      libraries/azurerm_ad_user.rb:3:in `load_with_context'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile_context.rb:160:in `instance_eval'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile_context.rb:160:in `load_with_context'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile_context.rb:149:in `load_library_file'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile_context.rb:136:in `block in load_libraries'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile_context.rb:134:in `each'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile_context.rb:134:in `load_libraries'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile.rb:256:in `load_libraries'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile.rb:248:in `block in load_libraries'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile.rb:233:in `each'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile.rb:233:in `each_with_index'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/profile.rb:233:in `load_libraries'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/runner.rb:87:in `block in load'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/runner.rb:81:in `each'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/runner.rb:81:in `load'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/inspec-3.4.1/lib/inspec/runner.rb:110:in `run'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/terraform/inspec.rb:46:in `exec'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/terraform/inspec_without_hosts.rb:29:in `exec'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/terraform/system.rb:87:in `execute_inspec'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/terraform/system.rb:74:in `verify'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/verifier/terraform.rb:155:in `verify'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/verifier/terraform.rb:162:in `block in verify_systems'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/verifier/terraform.rb:161:in `each'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/verifier/terraform.rb:161:in `verify_systems'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.9.0/lib/kitchen/verifier/terraform.rb:91:in `call'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:459:in `block in verify_action'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:552:in `synchronize_or_call'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:514:in `block in action'
D      D:/Ruby25-x64/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:513:in `action'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:451:in `verify_action'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:381:in `block in transition_to'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:380:in `each'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:380:in `transition_to'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/instance.rb:162:in `verify'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:198:in `public_send'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:198:in `run_action_in_thread'
D      D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/test-kitchen-1.25.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
```

**Comment by nukdcbear** [comment] 2019-11-01 18:20
To follow up if I utilize gem 'activesupport', '~> 5.2.3' in the Gemfile and execute bundle kitchen verify it appears inspec picks up none of the terraform output -json information as all of the tests fail reporting nothing returned.

**Comment by jagregory** [comment] 2019-11-04 09:39
I'm seeing the same error without kitchen-terraform in the picture. Just running inspec 4.18.24 against an Azure resource results in an `active_support/core_ext/hash` error.

```
1: from /opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/inspec/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- active_support/core_ext/hash (LoadError)
```

**Comment by r-fennell** [comment] 2019-11-13 10:39
Thank you for opening this issue. 
Looking into this, it appears this issues stems from the `active_support` dependency being added in version 1.5.0 of inspec-azure.
While we work on a fix you may wish to pin to the previous version of inspec-azure in your inspec.yml:
```
depends:
  - inspec-azure:
  url: https://github.com/inspec/inspec-azure/archive/v1.4.3.tar.gz
```

**Comment by williamayerst** [comment] 2019-11-18 13:08
Came across this same problem, this got me past, thank you.

**Comment by r-fennell** [comment] 2019-11-27 16:34
Hi @nukdcbear 
I believe this has now been fixed, can you confirm if this issue is resolved for you using the following versions:
inspec: >= v4.18.39
inspec-azure: >= v1.9.5

Thanks

**Comment by damianl-ubs** [comment] 2019-12-02 15:40
It doesn't seem to be fixed:
```yaml
depends:
  - name: inspec-azure
    git: https://github.com/inspec/inspec-azure
    version: 1.9.6
```
`inspec version: 4.18.39`

Error still remains:
`require: cannot load such file -- active_support/core_ext/hash (LoadError)`

In version 1.4.1 (at least in my case) command `inspec compliance upload inspec_dir` was working properly

**Comment by pag-r** [comment] 2019-12-02 15:45
It doesn't seem to be fixed:
```yaml
depends:
  - name: inspec-azure
    git: https://github.com/inspec/inspec-azure
    version: 1.9.6
```
`inspec version: 4.18.39`

Error still remains:
`require: cannot load such file -- active_support/core_ext/hash (LoadError)`

In version 1.4.1 (at least in my case) command `inspec compliance upload inspec_dir` was working properly

**Comment by r-fennell** [comment] 2019-12-03 14:35
Hi @pag-r 
Thank you for the feedback. 
I've tested this again and have found the latest version(s) to be working as expected. I'll add my configuration below. Can you please add your own and any other steps you took to replicate your issue?

```
$ gem list inspec train

*** LOCAL GEMS ***

inspec (4.18.39)
inspec-bin (4.18.39)

*** LOCAL GEMS ***

train (3.2.0)



$ inspec --version
4.18.39



$ cat inspec.yml
name: azuretest
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
depends:
  - name: inspec-azure
    git: https://github.com/inspec/inspec-azure
    version: 1.9.6
supports:
  platform: azure
```

Thanks

**Comment by pag-r** [comment] 2019-12-03 15:39
Hi @r-fennell,

First, thanks for your support.

Commands I'm using:
```shell
$ inspec compliance login --insecure https://chef.automate --token="secure_token" --user=myuser
$ inspec vendor my-cis-azure-foundations/ --overwrite
$ inspec compliance upload my-cis-azure-foundations/

$ gem list inspec train

*** LOCAL GEMS ***

debug_inspector (0.0.3)
inspec (4.18.39)
inspec-bin (4.18.39)
kitchen-inspec (1.3.1)

*** LOCAL GEMS ***

train (3.1.8)
train-aws (0.1.13)
train-core (3.1.8)
train-habitat (0.2.13)
train-winrm (0.2.5)
$ inspec --version
4.18.39
$ rpm -qa | grep chef
chef-workstation-0.12.20-1.el7.x86_64

```

Below inspec.yml
```yml
name: my-cis-azure-foundations
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
supports:
  platform: azure
inspec_version:
- ">= 3.0.9"
depends:
- name: inspec-azure
  git: https://github.com/inspec/inspec-azure
  version: 1.9.6
```

I see that `train` version is lower the yours, so it can generate error, but I don't think I will be able to update single gem due to air-gapped env. So most probably I will have to wait for a chef-workstation update.

Error still the same:
`Uploading to Chef Automate
Error during profile upload:
rpc error: code = InvalidArgument desc = Check InSpec check failed for /hab/svc/compliance-service/var/tmp/inspec-upload674178769.tar.gz with message: exit status 1
/hab/pkgs/core/ruby/2.5.5/20190416223112/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in require: cannot load such file -- active_support/core_ext/hash (LoadError)`

**Comment by gsreynolds** [comment] 2019-12-09 15:03
Just to note here, there are two instances of InSpec involved here. InSpec on the workstation and InSpec on the Automate 2 server. The error message is coming from `inspec check` being executed against the uploaded profile on the Automate 2 server. A PR to bump InSpec on Automate 2 has already been merged (https://github.com/chef/automate/pull/2226), just awaiting release.

**Comment by gsreynolds** [comment] 2019-12-09 18:34
Automate 2 version 20191129172405 released a few hours ago includes InSpec 4.18.39.

https://discourse.chef.io/t/automate-2-version-20191129172405-released/16335

**Comment by gsreynolds** [comment] 2019-12-11 12:57
Looks like whilst Automate 20191129172405 shipped with InSpec 4.18.39, it's not quite the right version of Train - 3.1.4 instead of 3.1.8 which is where the active_support gem is added into train's dependencies (https://github.com/inspec/train/blob/master/CHANGELOG.md#v318-2019-11-18)
```
/hab/pkgs/chef/inspec/4.18.39/20191114233129/lib/gems/train-3.1.4
```

**Comment by gsreynolds** [comment] 2020-01-30 17:53
Just to circle back here, latest Automate release is 20200123225613 which ships with InSpec 4.18.51 (https://github.com/chef/automate/pull/2521) which bundles train-3.2.0 and thus activesupport-5.2.4 gems, so this should be resolved.

```
/hab/pkgs/chef/inspec/4.18.51/20191211220937/lib/gems/train-3.2.0
```

**Comment by damianl-ubs** [comment] 2020-02-04 10:25
Hi All, newest version of Chef Automate (20200123225613) fixes the issue. Thanks @gsreynolds.

**Comment by pag-r** [comment] 2020-02-04 10:29
Hi All, newest version of Chef Automate (20200123225613) fixes the issue. Thanks @gsreynolds.

**Comment by rmoles** [comment] 2020-02-05 10:08
Closing, as the issue is now resolved 😄

**Closed by rmoles** 2020-02-05 10:08 UTC
